### ISSUE TITLE
Significant disparity in the scale of distance

### ISSUE THREAD

**Issue by zzzyf01** [naver-ai/pcmepp#5]
Dear Author, I attempted to apply this method on other datasets; however, I encountered a significant disparity in the scale of the distance of the mean and the distance of the variance when calculating the loss. While the mean was L2 normalized, the variance remained unnormalized. This thousand-fold difference in scale poses challenges for proper network training. Could you kindly suggest a solution to address this issue?

**Comment by SanghyukChun** [comment]
Hi, thanks for your question.
Could you give me more detailed explanations?
$\mu$ and $\sigma^2$ might have different scales by its design. I cannot understand why it makes your network training challenging.
If you give me a more detailed example when your network training unstable, it will be very helpful to me for answering your question

**Comment by zzzyf01** [comment]
The scale difference between $\mu$ and $\sigma^2$ has led to a significant disparity in their contribution to the loss during training. As a result, the loss derived from $\sigma^2$ quickly decreases, while the loss associated with $\mu$ remains almost unchanged. From my perspective, it seems that the constraints on $\mu$ are more crucial for the model's accuracy. Despite the rapid decline in the loss associated with $\sigma^2$ constraints, there has been no improvement in the accuracy during the inference stage.

**Comment by SanghyukChun** [comment]
The purpose of probabilistic representations is not to the best accuracy but to learn a proper probabilistic model.
Back to the original question,
(1) the loss does not suffer from "challenges for proper network training" as your initial question. The loss is numerically stable (it is a combination of l2 distance of means and the trace of the covariances). Therefore, the loss will not suffer from any challenge in terms of training stability
(2) $\sigma$ could be saturated to almost zero if there is no uncertain match in the dataset. Note that the purpose of the uncertainty module is to capture the "uncertainty" in terms of "confusing ground truth". In this case, the uncertainty comes from the many-to-many mapping of the image-caption matches. If your dataset has no confusing match or correspondence, the $\sigma$ will be collapsed to zero and it is an intended behavior.
(3) $\sigma$ shouldn't be large. It is for encoding the intensity of the uncertainty, not for achieving the best performance. However, too small $\sigma$ often causes numerical instability (because we have to take an exponential for the log variance, the output of the network). It is prevented by VIB loss (KL divergence between N(0, 1)), and other techniques such as pseudo-positives described in the paper.
