### ISSUE TITLE
probabilistic embedding question

### ISSUE THREAD

**Issue by makimon123** [naver-ai/pcmepp#6]
How are the mean and variance of the probability distribution of image embedding encoded?plz

**Comment by SanghyukChun** [comment]
Please check Fig 2 in the paper.
There are two heads; one is for mean, and the other is for log variance. Using the outputs, we can use the re-parameterization trick to generate a probability distribution.

<img width="945" alt="image" src="https://github.com/naver-ai/pcmepp/assets/4919315/5b0899ce-93fd-4e0b-91fa-e582a043d040">

**Comment by makimon123** [comment]
Thx！ But I noticed a difference in this project with the previous PCME,  What to pay attention to when designing the head?

**Comment by SanghyukChun** [comment]
Basically, I don't want to limit PCME or PCME++ to a specific architecture; I think both of them are about the algorithm rather than architecture.
However, in terms of implementation, PCME is based on GRU and ResNet, and PCME++ is based on the CLIP ViT backbone. Namely, PCME++ image and text encoders are both Transformers, and the additional heads are the additional Transformer blocks. It makes the overall architecture simpler, and easy to scale up to larger backbone size.

**Comment by makimon123** [comment]
Thank you for the explanation and such a great work！
